CMake 3rdparty: Do not overwrite CMAKE_C(XX)_FLAGS
It causes at least problems on sysrooted builds as e.g Openembedded/Yocto

| /home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/lmms/1.2.0-r0/git/src/3rdparty/rpmalloc/rpmalloc/rpmalloc/rpmalloc.c:102:12: fatal error: unistd.h: No such file or directory
|  #  include <unistd.h>
|             ^~~~~~~~~~
| compilation terminated.

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>