Use system fltk to avoid linker error
Error when building RemoteZynAddSubFx:

/usr/bin/ld:
/__w/lmms/lmms/build/vcpkg_installed/x64-linux/tools/fltk/../../lib/libfltk.a(Fl_x.cxx.o):
undefined reference to symbol 'XConvertSelection'
/usr/bin/ld:
/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libX11.so.6:
error adding symbols: DSO missing from command line